const SET_FILTER = "SET_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";

const SET_SORT = "SET_SORT";
const CLEAR_SORT = "CLEAR_SORT";

const SET_USERS = "SET_USERS";

export { SET_FILTER, CLEAR_FILTER, SET_SORT, CLEAR_SORT, SET_USERS };
